
services:
  app:
    build: .
    container_name: my-node-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    restart: always

  db:
    image: mysql:8
    container_name: my-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

volumes:
  mysql-data:
